Repository Synergile/Synergile, pull requests merged in 2020-08, with the labels that each got.

#42 Cog master
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  __init__.py
  bot.py
  commands/8ball.py
  commands/ban.py
  commands/build_info.py
  commands/choose.py
  commands/help.py
  commands/kick.py
  commands/loadCommand.py
  commands/music.py
  commands/ping.py
  commands/profile.py
  commands/purge.py
  commands/reloadCommand.py
  commands/restart.py
  commands/sh_info.py
  commands/unloadCommand.py
  commands/uptime.py
  requirements.txt
  util/delay.py
  util/discordutil.py
  util/parseTime.py
  util/pyutil.py
  util/stringbuilder.py
Labels: enhancement, help wanted

#48 Fix help command collision
  bot.py
Labels: bugfix

#55 Autodeploy
  .github/workflows/deploy.yml
  Pipfile
  Pipfile.lock
  bot.py
Labels: enhancement

#52 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: suggestion
