Repository Synergile/Synergile, pull requests merged in 2020-05, with the labels that each got.

#3 Added : for sanity
  bot.py
Labels: P3

#15 Create buildinfo.conf
  buildinfo.conf
Labels: documentation

#18 Auto role for Member
  bot.py
Labels: enhancement

#17 Profile accept id
  bot.py
Labels: enhancement

#23 add-generic-error-handler
  bot.py
Labels: enhancement

#26 Kickban resolve input
  bot.py
Labels: enhancement

#20 Cog implementation
  bot.py
Labels: enhancement

#30 Utils
  .gitignore
  __init__.py
  bot.py
  commands/__pycache__/uptime.cpython-37.pyc
  commands/uptime.py
  util/discordutil.py
  util/pyutil.py
  util/stringbuilder.py
Labels: enhancement

#31 changed commands.bot to commands.autoshardedbot for sharding
  bot.py
Labels: enhancement

#33 Profile kick ban cog
  bot.py
  commands/ban.py
  commands/kick.py
  commands/profile.py
  commands/uptime.py
  util/pyutil.py
  util/stringbuilder.py
Labels: enhancement

#37 Shinfo cog
  commands/sh_info.py
Labels: enhancement
