Repository Synergile/Synergile, pull requests merged in 2021-02, with the labels that each got.

#66 Clarify and expand upon README.md
  README.md
Labels: documentation

#62 Fix loading cogs
  .gitignore
  bot.py
  buildinfo.conf
  commands/ban.py
  commands/help.py
  configuration.py
  ensure_path.py
Labels: enhancement

#76 Add error handling to report missing permissions when using kick/ban
  commands/ban.py
  commands/kick.py
Labels: feature
